// Vercel Edge Middleware: HTTP Basic Auth for the entire site.
//
// Set the password via the SITE_PASSWORD environment variable in the Vercel dashboard
// (Project → Settings → Environment Variables). Password is auto-generated by
// deploy_full.sh — never hand-pick. Username is fixed below.

export const config = {
  matcher: '/((?!api/|_next/static|_next/image|favicon\\.ico).*)',
};

export default function middleware(req) {
  const VALID_USER = 'acorns-pr';
  const VALID_PASS = process.env.SITE_PASSWORD;

  if (!VALID_PASS) {
    return new Response(
      'Site configuration error: SITE_PASSWORD environment variable is not set in Vercel.',
      { status: 500 }
    );
  }

  const auth = req.headers.get('authorization');

  if (!auth) {
    return new Response('Authentication required', {
      status: 401,
      headers: {
        'WWW-Authenticate': 'Basic realm="VSCRL x Acorns PR Pulse"',
        'Content-Type': 'text/plain',
      },
    });
  }

  const [scheme, encoded] = auth.split(' ');

  if (scheme !== 'Basic' || !encoded) {
    return new Response('Unauthorized', {
      status: 401,
      headers: { 'WWW-Authenticate': 'Basic realm="VSCRL x Acorns PR Pulse"' },
    });
  }

  let decoded;
  try {
    decoded = atob(encoded);
  } catch (e) {
    return new Response('Bad auth header', { status: 400 });
  }

  const idx = decoded.indexOf(':');
  const user = decoded.slice(0, idx);
  const pass = decoded.slice(idx + 1);

  if (user !== VALID_USER || pass !== VALID_PASS) {
    return new Response('Invalid credentials', {
      status: 401,
      headers: { 'WWW-Authenticate': 'Basic realm="VSCRL x Acorns PR Pulse"' },
    });
  }

  // Auth OK — let the request through to the static files.
}
